export const locations = [
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://antenasanluis.mx/wp-content/uploads/2019/02/1366_2000-4-1000x600.jpg",
    superHost: true,
    stars: "4.40",
    info: "Entire apartment, 2 beds",
    description: "Stylist apartment in center of the city",
    city: "Helinki",
    country: "Finland",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://uploads-ssl.webflow.com/60112e9fafd96bcbbf1ed8cd/60cb82055333fd3e960e222e_decorar-apartamento-turi%CC%81stico-1.png",
    superHost: false,
    stars: "4.25",
    info: "Private room",
    description: "Cozy, peaceful and private room with...",
    city: "Helinki",
    country: "Finland",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://images.trvl-media.com/hotels/16000000/15370000/15362500/15362453/c09579f2_z.jpg",
    superHost: false,
    stars: "4.96",
    info: "Entire House",
    description: "Modern House in a remote area",
    city: "Helinki",
    country: "Finland",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/casa-playa-surf-dormitorio-terraza-exterior-madera-1627031472.jpg",
    superHost: true,
    stars: "4.85",
    info: "Entire apartment, 2 beds",
    description: "Stylist room in desig district",
    city: "New York",
    country: "USA",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://imagenesnoticias.canalrcn.com/ImgNoticias/Hospedaje.jpg",
    superHost: false,
    stars: "4.54",
    info: "Private room",
    description: "Modern apartment close to nature",
    city: "New York",
    country: "USA",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://motoryviajes.com/wp-content/uploads/2015/03/Hoteles-con-Encanto-Avion-Klm-Apartamento-1.jpg",
    superHost: false,
    stars: "4.64",
    info: "Entire house",
    description: "House in a remote area",
    city: "Cape Town",
    country: "South Africa",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://www.eluniversalpuebla.com.mx/sites/default/files/styles/f04-630x388/public/2022/04/05/airbnb-el-universal-puebla-lo-recuperado.jpg",
    superHost: true,
    stars: "4.75",
    info: "Entire house, 2 beds",
    description: "Stylist house in famous neighbourhood",
    city: "Cape Town",
    country: "South Africa",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://i2.wp.com/www.nognoginthecity.com/wp-content/uploads/2022/06/OMG-Listing-The-Boot-New-Zealand-scaled.jpg",
    superHost: false,
    stars: "4.55",
    info: "Private room",
    description: "Simple and eco-friendly apartment",
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://static-wc.arcux.net/uploads/20201020202131/acabados-2-2-975x650.jpg",
    superHost: false,
    stars: "4.33",
    info: "Entire house",
    description: "House in a remote area",
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://images.trvl-media.com/hotels/30000000/29900000/29898100/29898041/47a42d11_z.jpg",
    superHost: true,
    stars: "4.42",
    info: "Entire house, 2 beds",
    description: "Stylist house in famous neighbourhood",
    city: "Melbourne",
    country: "Australia",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://www.nuevamujer.com/resizer/Pv-17u5GQ86_qEuMmv4XhWJKymE=/800x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/ANZ64FD4UVBYLJANV4NSUOIV5E.jpg",
    superHost: false,
    stars: "4.90",
    info: "Private room",
    description: "Simple and eco-friendly apartment",
    city: "Melbourne",
    country: "Australia",
  },
  {
    id: "id" + Math.random().toString(16).slice(2),
    img: "https://www.contemporist.com/wp-content/uploads/2018/03/modern-glass-and-wood-cat-enclosure-120318-437-01.jpg",
    superHost: false,
    stars: "4.12",
    info: "Entire house",
    description: "House in a remote area",
    city: "Madrid",
    country: "Spain",
  },
];

export const places = [
  {
    cities: ["Madrid"],
    country: "Spain",
  },
  {
    cities: ["Melbourne"],
    country: "Australia",
  },
  { cities: ["New York", "Los Angeles"], country: "USA" },
  {
    cities: ["Cape Town"],
    country: "South Africa",
  },
  {
    cities: ["Helinki"],
    country: "Finland",
  }
];
